### ISSUE TITLE
Minimum Height of Level (prevent text overflow)

### ISSUE THREAD

**Issue by bitcalc** [jakezatecky/d3-funnel#12]
When `dynamicArea` is set to `true`, some levels can be so small that the labels overflow above them. I am going to look at setting a minimum height, have you looked into this before or do you want to wait for a pull request?

**Comment by bitcalc** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8331953/6837827/0fd694dc-d349-11e4-9da7-ba0de176b5ad.jpg)

**Comment by jakezatecky** [comment]
Thanks for the issue!

I was aware that this problem could surface, but decided to only address it if someone else made note of it. A minimum-height for each trapezoid would be a reasonable solution to this problem; the dynamic area would then be calculated against the remaining real estate.

I have been delaying any more radical features and fixes in anticipation that I will refactor the library for the 0.7 release, which should be much more maintainable (I have some unpushed commits). I was hoping to include in 0.7.1 more options relating to how the labels are drawn, but I can probably get around to implementing a minimum-height feature.

I should have more time over the weekend to look into implementing this. Of course, if you find that you have a solution you can submit a pull request! Otherwise, I should *eventually* resolve this.

**Comment by bitcalc** [comment]
I'm going to be honest, the maths is too complicated for me right now - I've never been good at graphics and it's gone midnight. I won't send a pull request because I don't know if what I've done is the right way of doing it here, I think I've simply beaten it into shape to fit my needs!

I've forked the repo and made the changes I needed, which works for me, so see if what I've done is right/wrong and let me know...

https://github.com/bitcalc/d3-funnel/commit/fd245c777d4d4d9c978ca21f903eb311efbc021a

_Oh, I can also remove the comments, they make sense to me, but you have the answers to clear them up._

**Comment by bitcalc** [comment]
OK, so the first commit was buggy, poor testing on my part, but this works: https://github.com/bitcalc/d3-funnel/commit/ea059df658f66d88fbb00aeb6aaf384085955386

**Comment by jakezatecky** [comment]
I looked at this. I have implemented a solution that works for any arbitrary height, but it doesn't have fault-detection mechanisms and can definitely be implemented in a cleaner manner. I'll work on procuring a cleaner commit.

**Comment by jakezatecky** [comment]
I went ahead and merged a commit that adds this option. It's not the most elegant of solutions, but in a future release, the calculation will be more elegant. See #14.
