### ISSUE TITLE
funnel chart not redraw when window size changed

### ISSUE THREAD

**Issue by tao-findly** [jakezatecky/d3-funnel#58]
Currently I have to redraw the funnel chart when window resize event fired, but this is not ideal because I only want to redraw the chart after container size is changed.

It would be great if the funnel chart can redraw itself after the the container size is changed.

**Comment by martinbutler** [comment]
Hi @tao-findly ,
you can add that yourself. here is an example with jquery:
$( window ).resize ( function () {
      chart.draw(funnel_data, funnel_options);
    } );

**Comment by tao-findly** [comment]
Hi @martinbutler,

Yes, I know I can use resize event to redraw the chart. But it's not efficient because the resize event fire too often.

What I find out is that I can set the <svg width="100%" /> to let the chart resize itself. But I don't know how to set the width as D3Funnel.width is number.

**Comment by jakezatecky** [comment]
Although DOM elements generally resize in response to resizing a window, a container can be resized even if the window does not resize (say through the use of JavaScript or CSS rules). In this scenario, a window resize event would clearly not capture the container resizing.

There is no native JavaScript way to monitor DOM element resizing (at least to my knowledge). I did find a library that claims to be able to attach resize events to DOM elements, thereby allowing you to add your own event to the container and redraw the funnel. Scroll to the end and you'll see a JavaScript event example.

http://marcj.github.io/css-element-queries/

Because this involves a third-party plugin and is a little more complex than I would like, there are no immediate plans to automatically make D3Funnel resize when its containing parent resizes. You are free to implement that yourself, however.

**Comment by tao-findly** [comment]
Hi @jakezatecky,

Thanks for your reply. I just realize that I haven't format my last comment properly so that you cannot see the most important part - `<svg width="100%" />`.  

My question is:
* Is that the right way using width="100%" to  resize the svg element? (It works in Chrome at least)
* If the answer is yes, can D3Funnel support it.

**Comment by jakezatecky** [comment]
If you set `width=100%` for an `<svg>`, that makes the SVG canvas bigger but the individual elements are still drawn in proportion to the original height. I think what you are referring to is more along the lines of the `viewbox` property of an `<svg>`. If an SVG was originally drawn with a width of 300px and a height of 400px, then the following SVG would effectively scale with whatever width its parent container is:

``` html
<svg viewBox="0 0 300 400" height="auto" width="100%">
    ...
</svg>
```
The caveat is that this will scale the width and height proportionally; that is, when the width increases so does the height of the funnel. That may be undesirable. You can add `preserveAspectRation="none"` to the SVG, which would disable this behavior, but then the resulting image is stretch and the text in particular looks awkward.

``` html
<svg preserveAspectRatio="none" width="100%" height="400px" viewBox="0 0 300 400">
    ...
</svg>
```

I suppose I could add an option to make the SVG scale in relation to its parent height, but both the height increase or the horizontal stretching are not optimal. The most visually appealing image is obtained by re-drawing the image, which cannot easily be done when the container resizes unless using a library as referred to above.

**Comment by tao-findly** [comment]
As your suggestion, I end up set follow attribute after the chart been drawn.
`d3.select(this.d3Chart.svg[0][0])`
     ` .attr('width', '100%')`
     ` .attr('viewBox', `0 0 ${this.d3Chart.width} ${this.d3Chart.height}`)`
     ` .attr('preserveAspectRatio', 'none');`

Yes, it's not optimal which rely on SVG scale. But I don't want to introduce another library for re-sizing only.

It would be great if you can support the scale option in the next release.

Once again thanks for your funnel chart library.

**Comment by jakezatecky** [comment]
I think it is relatively easy to leave it to a developer to make the attribute changes discussed above themselves. I am not too keen on adding this as an option because it's not that pretty.
