### ISSUE TITLE
Height issue when all values are zero 

### ISSUE THREAD

**Issue by pptyasar** [jakezatecky/d3-funnel#86]
When dynamic height is set and all values are zero than funnel is collapsed.

https://jsfiddle.net/wtsk2L97/485/

As request 
https://github.com/jakezatecky/d3-funnel/issues/70#issuecomment-399712519

**Comment by jakezatecky** [comment]
@pptyasar That issue is not nearly as pronounced in the latest version of the library. It appears your example is using v0.7.5 whereas the latest is v1.1.1. See the fork I created of that which shows that a funnel is rendered, although it does not fully respect the height:

https://jsfiddle.net/s4qjuxry/2/

I will be adding a fix that makes the funnel take up the remaining space in the instance that all values are zero.

**Comment by jakezatecky** [comment]
This should now be fixed. See https://jsfiddle.net/s4qjuxry/4/.

**Comment by pptyasar** [comment]
@jakezatecky  thanks
