### ISSUE TITLE
Traditional pyramid shape?

### ISSUE THREAD

**Issue by jh4rri** [jakezatecky/d3-funnel#91]
Hi,

I was wondering it is was possible to configure the funnel so that it looked like a traditional pyramid i.e. pointed at the smallest end?

thanks
Jane

**Comment by jakezatecky** [comment]
Good question. Simply set `chart.bottomWidth` to a value of `0` to get the traditional pointed end (of course, in this case, the bottom is the top because the funnel is inverted). Do note that because of this you should have enough height for the top-most block for any label to be properly legible.

Here is an example:

https://jsfiddle.net/jhr6nk70/

**Comment by jh4rri** [comment]
Hi,
Sorry for the late reply, I've been on holiday :)

I've been looking at your fiddle and I was wondering if there was a way of making the text wrap so that if you have a long label it doesn't disappear outside of the funnel?

I agree one issue with the pointed funnel is the lack of room for the label on the top most block.  Is there any way of having any control over the vertical alignment for this block?  i.e. the top most one or two could be aligned to the bottom where there is most space whilst the rest continue to have central vertical alignment?

many thanks for your reply and your jsfiddle

**Comment by jakezatecky** [comment]
You can add newlines (`\n`) to the text provided you know when it is going to overflow. [See this example.](https://jsfiddle.net/ur6ckehd/)

You can also hypothetically add a newline character at the beginning of the string to shift the rendered text down a bit on the chart, but it may not produce the result you want because all lines (including empty ones) are vertically centered in a group. Ironically, it _does_ work well in my [simple example](https://jsfiddle.net/gp2ca8bt/), although that is not guaranteed to work for any height.

Word wrap is definitely a feature I want to add (see #80) but it will take a little effort to implement. I might be able to work on that on the weekend.

I do see value in allowing the text to be aligned to the top and bottom in additional to the current middle behavior. I might add that as an additional feature for the overall chart and as well as allow it to also be set on a per-block basis.

**Comment by jakezatecky** [comment]
Hello. I am closing out this issue due to a lack of response. If you are still having an issue, feel free to reopen this.

I opened a separate issue, #96, which serves as a placeholder for an enhancement that would allow for labels to be aligned to the top or bottom of a block in addition to the current behavior.
